### ISSUE TITLE
有绕过下载上限的措施吗

### ISSUE THREAD

**Issue by waitfortea** [wing-ho/ximalaya#10]
我用python写了一个，但是下载次数大概500多次就会返回下载次数过多，

**Comment by wing-ho** [comment]
@waitfortea 我还没有试过一次下载那么集的，你发个链接，我有空试试看

**Comment by waitfortea** [comment]
web接口是多就一天1000次

> @waitfortea 我还没有试过一次下载那么集的，你发个链接，我有空试试看
