### ISSUE TITLE
显示任务完成，但是找不到下载的文件

### ISSUE THREAD

**Issue by baikourin** [wing-ho/ximalaya#3]
你好，
执行下面的命令
```node index.js https://www.ximalaya.com/youshengshu/15702663/102936835 .```
显示
`102936835任务完成！`
但是找不到下载的文件。不知道是否真的下载成功。

**Comment by wing-ho** [comment]
你好 @baikourin ，下载vip专辑需要修改代码中的身份认证的token，本人没有vip账号无法进行测试。
