### ISSUE TITLE
显示任务完成，也有产生“download”文件夹，但里面没有文件

### ISSUE THREAD

**Issue by zensgit** [wing-ho/ximalaya#4]
您好，执行node index.js https://www.ximalaya.com/ertongjiaoyu/11106118/  显示
p13任务完成！
然后也产生了download文件夹，然而这是个空的文件夹，找不到任何下载的文件，我该怎么做。

**Comment by wing-ho** [comment]
@zensgit 我更新了脚本，现在应该可以下载了
