### ISSUE TITLE
建议下载的档名前面加上编号

### ISSUE THREAD

**Issue by cj-neo** [wing-ho/ximalaya#7]
很好用，很方便，但是有些原本名称没有编号下载之后整个顺序乱掉了，所以建议在档名前面加上编号方便排序

PS.
1.如果可以的话编号还要补零例如 0001 ~ 0100 ~ 9999 方便排序
2.还有我发现目前下载是倒序下载，建议改成正序下载，倒序当然也可以但是编号可能就要注意一下 ...
3.有编号之后如果还有闲暇的时间还可以加上指定区段下载功能例如只下载 001~100 集这样就更方便了 XD

谢谢

**Comment by wing-ho** [comment]
@cj-neo 下载文件已经添加序号，有些专辑正反序跟实际标题的排序是相反的，如果出现相反的话，修改isAsc变量为false

**Comment by cj-neo** [comment]
> @cj-neo 下载文件已经添加序号，有些专辑正反序跟实际标题的排序是相反的，如果出现相反的话，修改isAsc变量为false

感恩阿！
